name: Chronicle API

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.12']

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies, VENV, Make Django Migrations
      run: |
        appfile=$(find ~/chronicle-runner -type f -name "*manage.py")
        appdir=$(dirname $appfile)
        cd $appdir
        echo "${{ secrets.CHRONICLE_ENV }}" > main/.env
        python3 -m venv chronicle-env
        source chronicle-env/bin/activate
        pip install -r requirements.txt
        python manage.py makemigrations users
        python manage.py makemigrations contact
        python manage.py makemigrations projects
        python manage.py makemigrations blog
        python manage.py makemigrations
        python manage.py migrate
        python manage.py collectstatic --noinput

    - name: Run Tests
      run: |
        envfile=$(find ~/chronicle-runner -type f -wholename "*chronicle-env/bin/activate")
        source $envfile
        python manage.py test
